# .bashrc

# source global definitions
if [ -f /etc/bashrc ]; then
   . /etc/bashrc
fi

# Add some aliases that I utilize
alias clean='rm -rf *~'
alias ll='ls -la'
export fpath=$fpath:/usr/local/share/zsh/site-functions/
